FROM nginxinc/nginx-unprivileged

COPY default.conf /etc/nginx/conf.d/default.conf

USER root

RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.16.3-amd64.deb

RUN sudo dpkg -i filebeat-7.16.3-amd64.deb

RUN filebeat modules enable nginx

COPY filebeat/filebeat.yml /etc/filebeat/filebeat.yml
COPY filebeat/nginx.yml /etc/filebeat/modules.d/nginx.yml

USER nginx

CMD service filebeat start && nginx -g daemon off